theme: jekyll-theme-primer
email: julien.savoie@protonmail.com
twitter_username: jzsavoie
github_username: jsavoie
author: Julien Savoie

# Social media
twitter_username: jzsavoie
github_username: jsavoie
